import sys,random,os,re

def infoinput():
	name = raw_input("Please input UM: ").strip()
	passwd = raw_input("Please input UM password: ").strip()
	if name.find(' ')!=-1 or passwd.find(' ')!=-1:
		print "can't contain whitespace!".title()
		sys.exit(1)
	return name,passwd


RandomRange = 128
SaltStart = 14
SaltEnd = 24
class Encryption(object):
	"""docstring for Encryption"""
	def __init__(self):
		pass
	def mapgen(self):
		""" generate random mapping list """
		keymap = []
		for x in range(0,RandomRange):
			keymap.append(random.randint(0,94))
		return keymap

	def encodeValue(self,value,keymap,reverse=False):
		""" encrypt string with random mapping list generated by mapgen() """
		encryValue = ''
		if len(value)<33:
			for x in range(0,len(value)):
				encryValue += chr(( ord(value[x]) - 33 + (lambda x : keymap[RandomRange-1-x] if reverse else keymap[x])(x) )%95 + 33) # lambda can be replace by (keymap[RandomRange-1-x] if reverse else keymap[x])
			encryValue += chr(1)
			for x in xrange(len(value)+1,32):
				encryValue += chr((keymap[RandomRange-1-x] if reverse else keymap[x]) + 33)
		elif len(value)<=RandomRange:
			for x in xrange(0,len(value)):
				encryValue += chr(( ord(value[x]) - 33+ (keymap[RandomRange-1-x] if reverse else keymap[x]) )%95 + 33)
		else:
			print 'your value is so long!'.title()
			sys.exit(1)
		return encryValue

	def writeConf(self,name,password):
		""" writing encrypted name&password to config file """
		with open('./info.conf','w') as conf:
			conf.writelines(
				"""[HADOOP-SVN-INFO]
baseurl  = http://svn.paic.com.cn/svn/pad_hadoop/trunk
user     = %s
password = %s
fileList = fileList.list"""%(name,password))

	def addSalt(self,keymap):
		""" add random salt to keymap generated by mapgen() """
		addsalt = keymap[:]
		for x in xrange(0,10):
			salt = random.randint(SaltStart,SaltEnd) - 32
			addsalt.insert(random.randint(0,len(keymap)),salt)
		return ''.join(chr(i + 32) for i in addsalt)

	def writepubkey(self,pubkey):
		""" store the pubkey value """
		if os.path.exists(r'pubkey.key'):
			os.system(r'attrib -H pubkey.key')
		with open("./pubkey.key", "w") as f:
			f.write(pubkey)
		os.system(r'attrib +H pubkey.key')


class Decryption(object):
	"""docstring for Decryption"""
	def clearKey(self):
		""" clear salt in pubkey written by Encryption.writepubkey() """
		keyValue = ''
		salt = re.compile('|'.join([chr(x) for x in range(SaltStart,SaltEnd+1)]))
		with open("./pubkey.key", "r") as f:
			keyValue = f.read()
		keyValue = salt.sub('', keyValue)
		return keyValue
	def decodeValue(self,value,reverse=False):
		keymap = self.clearKey()
		decryValue = ''
		index = value.find(chr(1))
		if index!=-1 and len(value)<=RandomRange:
			for x in xrange(0,index):
				decryValue += chr( (ord(value[x]) - 33 - (ord(keymap[RandomRange-1-x] if reverse else keymap[x])-32) )%95 +33 )
		elif len(value)<=RandomRange:
			for x in xrange(0,len(value)):
				decryValue += chr( (ord(value[x]) - 33 - (ord((lambda x:keymap[RandomRange-1-x] if reverse else keymap[x])(x))-32) )%95 + 33 )
		else:
			print "value is so long! cut it please!".title()
			sys.exit(1)
		return decryValue

# =================== encryption process
# encry = Encryption()
# encryKey = encry.mapgen()
# name, password = infoinput()
# encry.writeConf( encry.encodeValue(name, encryKey), encry.encodeValue(password, encryKey, True) )
# encry.writepubkey(encry.addSalt(encryKey))

# =================== decryption process
decry = Decryption()
print decry.decodeValue("""@7RfVQcv.FEK*oT:segtK<uiS#9_y""")
print decry.decodeValue("""E#tqbuiVG+Th0ji\9*[\`yZB`;5py^V""",True)
# print -1%95

# encry = Encryption()
# encryKey = encry.mapgen()
# encryValue01 = encry.encodeValue('CHENGSIQIN754', encryKey)
# encryValue02 = encry.encodeValue('passwordofmine', encryKey, True)
# print encryValue.index(chr(1))
# print encryValue01[:encryValue01.find(chr(1))]
# print encryValue02[:encryValue02.find(chr(1))]
# encry.writeConf(encryValue01,encryValue02)


# print encryKey
# print len(encryKey)
# print [chr(i+32) for i in encryKey]
# print ''.join(chr(i) for i in encryKey)
# print encry.addSalt(encryKey)
# writepubkey(encry.addSalt(encryKey))


# print decry.clearKey()
# print repr(clearKey())
# print len(decry.clearKey())



# value = 'CHENGSIQIN754'
# print ord(value[0])

# print [value[x] for x in range(0,len(value))]

# print mapgen()[:32]

# print [chr(x) for x in xrange(33,127)]
# print [chr(x) for x in xrange(0,256)]
# print [ord(chr(x)) for x in xrange(0,256)]
# print [chr(x) for x in range(14,32)]
# print '|'.join([chr(x) for x in range(14,32)])

# saltValue = addSalt(encryKey)
# print saltValue
# pattern = re.compile('|'.join([chr(x) for x in range(14,32)]))
# print pattern.sub('', saltValue)
# print saltValue


# with open("./test.key","w") as w:
# 	w.write('M'.join([chr(x) for x in range(14,24)]))
# with open("./test.key", "r") as f:
# 	keyValue = f.read()
# with open("./pubkey.key", "r") as f:
# 	keyValue02 = f.read()
# print repr(keyValue)
# print repr(keyValue02)

